#FIXME change file name to actual app name
#FIXME change to actual app name
name: $hyoo_template_demo

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'hyoo/template' #FIXME namespace of this package
        modules: 'demo' #FIXME which modules to build, remove line if only on module at the root
    
    #FIXME remove one of the following
    
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./mol/template/demo/-/package.json #FIXME path to build module
        
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      if: github.ref == 'refs/heads/master'
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: 'hyoo/template/demo/-' #FIXME path to build app
